---
title: "DATA_605_Assignment_14"
author: "Joshua Sturm"
date: "May 13, 2018"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    highlight: textmate
    theme: sandstone
    code_folding: show
    toc: yes
    toc_float: yes
    smart: yes
  github_document:
always_allow_html: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, collapse = T)
```

# Task

This week, we'll work out some Taylor Series expansions of popular functions.

\[
f(x) = \frac{1}{(1-x)}
\]

\[
f(x) = e^x
\]

\[
f(x) = \ln(1 + x)
\]

For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as a R-Markdown document.

# 1.
The formula for a Taylor Series centered about $c$ is 
\begin{gather*}
f(x) = f(c) + f'(c)(x-c) + \frac{f''(c)}{2!} + \cdot\cdot\cdot \\
= \sum_{n=0}^{\infty}\frac{f^{(n)}(c)}{n!}x^n
\end{gather*}

If this is centered about 0, aka a Maclaurin Series, we get:

\begin{gather*}
1 + x + x^2 + x^3 + \cdot\cdot\cdot \\
= \sum_{n = 0}^{\infty}x^n \ \ \ x \in (-1, 1)
\end{gather*}

This is basically a geometric series.

# 2.
Centered about 0:

\begin{gather*}
1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \cdot\cdot\cdot \\
= \sum_{n = 0}^{\infty} \frac{x^n}{n!} \ \ \ x \in \mathbb{R}
\end{gather*}

# 3.
Centered about 0:

\begin{gather*}
0 + x - \frac{1}{2!}x^2 + \frac{2}{3!}x^3 - \frac{6}{4!}x^4 + \cdot\cdot\cdot \\
= \sum_{n = 0}^{\infty}(-1)^{n+1}\frac{x^n}{n} = \sum_{n = 0}^{\infty}(-1)^{n-1}\frac{x^n}{n} \ \ \ x \in (-1, 1]
\end{gather*}