---
title: "DATA 605 - Assignment 5"
author: "Joshua Sturm"
date: "03/04/2018"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    highlight: pygments
    theme: cerulean
    code_folding: show
    toc: yes
    toc_float: yes
    smart: no
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, collapse = T)
```

# Question 1
A box contains 54 red marbles, 9 white marbles, and 75 blue marbles. If a marble is randomly selected from the box, what is the probability that it is red or blue? Express your answer as a fraction or a decimal number rounded to four decimal places.

## Solution
Since $P(A)$ and $P(B)$ are disjoint, $P(A \cup B) = P(A) + P(B)$.

$P(R) = \frac{54}{138}, \hspace{5mm} P(B) = \frac{75}{138}, \hspace{5mm} P(A \cup B) =$ `r round(54/138 + 75/138, 4)`.

# Question 2 
You are going to play mini golf. A ball machine that contains 19 green golf balls, 20 red golf balls, 24 blue golf balls, and 17 yellow golf balls, randomly gives you your ball. What is the probability that you end up with a red golf ball? Express your answer as a simplified fraction or a decimal rounded to four decimal places.

## Solution
$P(R) = \frac{20}{80}$ = `r round(20/80, 4)`.

# Question 3
A pizza delivery company classifies its customers by gender and location of residence. The research department has
gathered data from a random sample of 1399 customers. The data is summarized in the table below.

\begin{center}
\begin{tabular}{ | c | c | c | }
 \hline
 \multicolumn{3}{|c|}{\textbf{Gender and Residence of Customers}} \\
 \hline
  & \textbf{Males} & \textbf{Females}\\
 \hline
 \textbf{Apartment} & 81 & 228\\
 \hline
 \textbf{Dorm} & 116 & 79\\
 \hline
 \textbf{With Parent(s)} & 215 & 252\\
 \hline
 \textbf{Sorority/Fraternity House} & 130 & 97\\
 \hline
 \textbf{Other} & 129 & 72\\
 \hline
\end{tabular}
\end{center}

What is the probability that a customer is not male or does not live with parents? Write your answer as a fraction or a
decimal number rounded to four decimal places.

## Solution
There are two ways to solve this problem: a simpler method, and a little more calculative method. I'll begin with the latter.

$P(M) = \frac{671}{1399}$ = `r round(671/1399, 4)` \ \ $\to P(M^{\complement}) = 1 - \frac{671}{1399} =$ `r round(1 - 671/1399, 4)`. 

Let $N$ be the event that the customer does not live with their parents.

$P(N) = 1 - P(N^{\complement}) = 1 - \frac{215 + 252}{1399} =$ `r round(1 - ((215 + 252)/1399), 4)`.

$P(M^{\complement} \cap N) = \frac{228 + 79 + 97 + 72}{1399} =$ `r round((228+79+97+72)/1399, 4)`. 

Since these events are clearly not disjoint, we use a slightly modified formula.

$P(M^{\complement} \cup N) = P(M^{\complement}) + P(N) - P(M^{\complement} \cap N) =$ `r round(0.5204 + 0.6662 - 0.3402, 4)`.

The simpler method would be to subtract the opposite; that is, the probability that the customer $\textit{is }$ male $\textit{and }$ lives with their parents.

$P(M^{\complement} \cup N) = 1 - P(M \cap N^{\complement}) = 1 - \frac{215}{1399} =$ `r round(1 - 215/1399, 4)`.

# Question 4
Determine if the following events are independent.
  - Going to the gym.
  - Losing weight. 
  
## Solution
They're dependent, since going to the gym increases the probability of losing weight.

# Question 5
A veggie wrap at City Subs is composed of 3 different vegetables and 3 different condiments wrapped up in a tortilla. If
there are 8 vegetables, 7 condiments, and 3 types of tortilla available, how many different veggie wraps can be made?

## Solution
Since ordering doesn't matter, we can calculate it as $\binom{8}{3}\times\binom{7}{3}\times\binom{3}{1}$ = `r choose(8,3)*choose(7,3)*choose(3,1)`.

# Question 6
Determine if the following events are independent.
Jeff runs out of gas on the way to work. Liz watches the evening news. 

## Solution
They're independent, since neither event affects the probability of the other event happening.

# Question 7
The newly elected president needs to decide the remaining 8 spots available in the cabinet he/she is appointing. If there
are 14 eligible candidates for these positions (where rank matters), how many different ways can the members of the
cabinet be appointed?

## Solution
Since ordering matters, we're looking for the number of permutations: $P(14,8) = \frac{14!}{6!} = `r factorial(14)/factorial(6)`$. 

# Question 8
A bag contains 9 red, 4 orange, and 9 green jellybeans. What is the probability of reaching into the bag and randomly
withdrawing 4 jellybeans such that the number of red ones is 0, the number of orange ones is 1, and the number of green
ones is 3? Write your answer as a fraction or a decimal number rounded to four decimal places.

## Solution
Since order doesn't matter, we're looking for a combination.

Total number of combinations: $\binom{22}{4} =$ `r choose(22,4)`.

The probability of picking 0 reds: $\binom{9}{0} = 1$.

Probability of picking one orange: $\frac{\binom{4}{1}}{7315} = `r choose(4,1)/choose(22,4)`$.

Probability of picking three green: $\frac{\binom{9}{3}}{7315} =$ `r choose(9,3)/choose(22,4)`.

So $P(1O3G) = \frac{4\cdot 84}{7315} =$  `r round((choose(4,1) * choose(9,3)) / choose(22,4), 4)`.

# Question 9
Evaluate the following expression: $\frac{11!}{7!}$.

## Solution
$\frac{11!}{7!} = 11 \cdot 10 \cdot 9 \cdot 8 =$ `r 11 * 10 * 9 * 8`. 

# Question 10
Describe the complement of the given event. 67% of subscribers to a fitness magazine are over the age of 34. 

## Solution
$P(F > 34) = 0.67$

$P((F > 34)^{\complement}) = 1 - P(F > 34) = 1 - 0.67$ =  `r 1 - 0.67`.

33% of subscribers to a fitness magazine are $\leq$ the age of 34.

# Question 11
If you throw exactly three heads in four tosses of a coin you win \$97. If not, you pay me \$30.

Step 1. Find the expected value of the proposition. Round your answer to two decimal places.

Step 2. If you played this game 559 times how much would you expect to win or lose? (Losses must be entered as
negative.)

## Solution
Let $W$ be the event that I win. The sample space for $W$ is $\Omega = \{HHHT, HHTH, HTHH, THHH\}$.

So, $P(W) = \frac{4}{2^4} = \frac{1}{4} \hspace{8mm}$ and $P(W^{\complement}) = 1 - \frac{1}{4} = \frac{3}{4}$.

1) The expected value is: $$E[x] = \sum_{i=1}^{\infty} x_{i}p_{u}$$

$E[x] = \frac{1}{4}\cdot97 - \frac{3}{4}30$ = `r 97/4-90/4`.

2) After 559, we'd expect to earn or lose $559 \cdot E[x] =$ `r 559 * 1.75`.

# Question 12
Flip a coin 9 times. If you get 4 tails or less, I will pay you \$23. Otherwise you pay me \$26.

Step 1. Find the expected value of the proposition. Round your answer to two decimal places.

Step 2. If you played this game 994 times how much would you expect to win or lose? (Losses must be entered as
negative.)

## Solution
Let $W$ be the event that I win.

0 Tails: $\binom{9}{0} = 1$.

1 Tail: $\binom{9}{1} = 9$.

2 Tails: $\binom{9}{2} = 36$.

3 Tails: $\binom{9}{3} = 84$.

4 Tails: $\binom{9}{4} = 126$.

$\Omega = \{2^9\} = 512$.

$P(W) = \frac{\sum W}{\Omega} = \frac{256}{512} = \frac{1}{2} = 0.5$.

$P(W^{\complement}) = \frac{1}{2} = 0.5$.

1) $E[x] = 23\cdot 0.5 - 26\cdot 0.5 =$ `r round(23/2 - 26/2, 2)`.

2) $994\cdot E[x] = 994\cdot(-1.50) =$ `r round(994*-1.50, 2)`.

# Question 13
The sensitivity and specificity of the polygraph has been a subject of study and debate for years. A 2001 study of the
use of polygraph for screening purposes suggested that the probability of detecting a liar was .59 (sensitivity) and that
the probability of detecting a "truth teller" was .90 (specificity). We estimate that about 20% of individuals selected for
the screening polygraph will lie.

a. What is the probability that an individual is actually a liar given that the polygraph detected him/her as such? (Show
me the table or the formulaic solution or both.)

b. What is the probability that an individual is actually a truth-teller given that the polygraph detected him/her as
such? (Show me the table or the formulaic solution or both.)

c. What is the probability that a randomly selected individual is either a liar or was identified as a liar by the
polygraph? Be sure to write the probability statement.

## Solution
Sensitivity = Correctly identify those with the attribute.

Specificity = Correctly identify those without the attribute.

Let $L$ be the event that the selected individual is a liar.

$P(L) = 0.20 \ \ \to P(L^{\complement}) = 0.80$.

Let $DL$ be the event that a liar is detected, and $DT$ be the event that a truth-teller was detected.

$P(DL|L) = 0.59 \ \ \to P(DL^{\complement}|L) = 0.41$.

$P(DT|T) = 0.90 \ \ \to P(DT^{\complement}|T) = 0.10$.

Using Bayes' Theorem:

1) $P(L|DL) = \frac{P(DL|L)P(L)}{P(DL|L)P(L) + P(DL|L^{\complement})P(L^{\complement})}$

$P(L|DL) = \frac{0.59\cdot 0.20}{(0.59\cdot 0.20 + 0.1\cdot 0.80)} = 0.\overline{5959}$.

2) $P(T|DT) = \frac{P(DT|T)P(T)}{P(DT|T)P(T) + P(DT|T^{\complement})P(T^{\complement})}$

$P(T|DT) = \frac{0.90\cdot 0.80}{(0.90\cdot 0.80 + 0.41\cdot 0.20)} = 0.8978$.

3) Since the events $L$ and $DL$ are not disjoint, we use the formula $P(L \cup DL) = P(L) + P(DL) - P(L \cap DL)$

To simplify, we can make use of DeMorgan's Law:

$P(L \cup DL) = 1 - P(L \cup DL)^{\complement} = 1 - P(L^{\complement}\cap DL^{\complement})$

$\to 1 - (0.90 \cdot 0.80_ = 0.28$.
